### ISSUE TITLE
How to use environment variables?

### ISSUE THREAD

**Issue by andremanoel** [ebondu/angular2-keycloak#15]
In applications that use automated deploy it is necessary to inject the environment variables in the angular application.
It is necessary to have another form of configuration besides the file keycloak.json
What is the best way to include the settings through the environment variables?

**Comment by ebondu** [comment]
Hi,
You may use differents keycloak.json files and then use [angular environnements](http://tattoocoder.com/angular-cli-using-the-environment-option/) to set proper the file name when initializing the lib ?

**Comment by ebondu** [comment]
This functionality is now implemented in ng6 branch (v1.1.0)
