### ISSUE TITLE
Invalid parameter: redirect_uri (v 0.9 )

### ISSUE THREAD

**Issue by pako-g** [ebondu/angular2-keycloak#17]
I have a problem with client redirection, when i run **ng serve**, it all works perfectly but when click login
get this error

![schermata del 2017-08-25 15-36-06](https://user-images.githubusercontent.com/17761109/29717162-6cf16bce-89ae-11e7-8945-e78a60a68110.png)

![schermata del 2017-08-25 15-36-50](https://user-images.githubusercontent.com/17761109/29717173-76d67562-89ae-11e7-85cd-dfb61339ef8d.png)

![schermata del 2017-08-25 15-37-07](https://user-images.githubusercontent.com/17761109/29717180-7c4aa28e-89ae-11e7-8e2f-0307c15c115f.png)

and this is my keycloak client

![schermata del 2017-08-25 15-42-26](https://user-images.githubusercontent.com/17761109/29717210-9bdf29da-89ae-11e7-86fe-f6a6cdb362b3.png)

the url inside keycloak is:
`http://localhost:8080/auth/realms/onkalo/protocol/openid-connect/auth?client_id=onakalo-public&redirect_uri=http%3A%2F%2Flocalhost%3A4200%2Fonkalo-angular&state=fd07d718-cb27-e8c9-8793-42fbe7bed93c&nonce=b5f2b15c-8e6b-cb44-163e-6b4ad1bc055e&response_mode=fragment&response_type=code&scope=openid`

this is keycloak log
`15:39:28,229 WARN  [org.keycloak.events] (default task-58) type=LOGIN_ERROR, realmId=onkalo, clientId=onakalo-public, userId=null, ipAddress=127.0.0.1, error=invalid_redirect_uri, redirect_uri=http://localhost:4200/onkalo-angular`

Maybe I have to build, because the problem is `vendor.bundle.js`
I also tried to pass the url in the login method but not work:
```
login() {
    this.keycloak.login({ redirectUri: 'http://localhost:4200/onkalo-angular' });
  }
```

**Comment by ebondu** [comment]
I guess the redirect URI does not match (port 8080 vs 4200), you must to add both URLs in the console.

**Comment by pako-g** [comment]
I also tried to include the url http://localhost:8080 but it does not work
not redirect to keycloak and the url show:
`http://localhost:4200/onkalo-angular/#error=unsupported_response_type&error_description=Client+is+not+allowed+to+initiate+browser+login+with+given+response_type.+Standard+flow+is+disabled+for+the+client.&state=a3506271-2c49-3609-511b-0b9b54d2fa86`

log of keycloak server
`16:25:58,959 ERROR [org.keycloak.services] (default task-52) KC-SERVICES0095: Client is not allowed to initiate browser login with given response_type. Standard flow is disabled for the client.`

`16:25:58,960 WARN  [org.keycloak.events] (default task-52) type=LOGIN_ERROR, realmId=onkalo, clientId=onakalo-public, userId=null, ipAddress=127.0.0.1, error=not_allowed, response_type=code, redirect_uri=http://localhost:4200/onkalo-angular/, response_mode=fragment`

I try to wrap it into a war file so you can do it all on the same port

**Comment by pako-g** [comment]
Just set it in keycloak client `Standard Flow Enabled: ON`
thanks a lot
