### ISSUE TITLE
Update for Angular 4.3 HttpClient

### ISSUE THREAD

**Issue by marcojahn** [ebondu/angular2-keycloak#19]
Hi,

are there any plans updating the library to work with Angular 4.3+ new HttpClient module ?

kind regards

**Comment by ebondu** [comment]
Hi,
There is no plan at the moment but I guess the implementationt could be simplified by using interceptors.

**Comment by jderuere** [comment]
Hi,

Having the same problem, my interceptor look like this: 

`@Injectable()
export class TokenInterceptor implements HttpInterceptor {

  constructor(private keycloak: Keycloak) {
  }

  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    const token = this.keycloak.accessToken;
    if (token) {
      const authReq = req.clone({setHeaders: {Authorization: token, Bearer: token}});
      return next.handle(authReq);
    } else {
      return next.handle(req);
    }
  }
}
`

but the accesToken is not provide after authentication. Any clue?

**Comment by ebondu** [comment]
See ng6 branch. Version 1.1.0 is has been tested with angular version 6.2.4.
