### ISSUE TITLE
ERROR in Ng2KeycloakModule is not an NgModule

### ISSUE THREAD

**Issue by natedouds** [ebondu/angular2-keycloak#6]
Trying to integrate this into my angular 4 app.
 - Angular 4.0.0
 - Angular Cli 1.0.3
 - TypeScript 2.2.0

Getting the following error when I try to import the module and run 'ng build':

ERROR in Ng2KeycloakModule is not an NgModule

**Comment by togbyte** [comment]
try to update the module.

export function httpFactory( backend: XHRBackend,
    defaultOptions: RequestOptions,
    keycloakAuth: KeycloakAuthorization,
    keycloak: Keycloak ) {
    return new KeycloakHttp( backend, defaultOptions, keycloak, keycloakAuth )
}

@NgModule( {
    imports: [HttpModule],
    declarations: [],
    providers: [Keycloak, KeycloakAuthorization, KeycloakHttp,
        {
            provide: Http,
            useFactory: httpFactory,
            deps: [XHRBackend, RequestOptions, Keycloak, KeycloakAuthorization]
        }],
    exports: []
} )

**Comment by scracho** [comment]
I am getting the same problem, I tried the update you post but I still get the same error

**Comment by natedouds** [comment]
Yea, I also tried your suggestion and am getting the same error. Additionally, I tried it with Angular Cli 1.0.3 and 1.0.6; same thing in both cases.

**Comment by ebondu** [comment]
You can try with version 0.8.1, I tried with a fresh angular 4 project (4.2.5) + angular-cli 1.2.0.

**Comment by joshisimt** [comment]
I am getting this error- 
ERROR Error: Uncaught (in promise): Error: No provider for Keycloak!
Error: No provider for Keycloak!

Even I have this dependancy added in package.json-     "@ebondu/angular2-keycloak": "^0.8.1",

and I have installed them too.

Please help.

**Comment by ebondu** [comment]
Hi,
did you add Keycloak as a provider in your component ? 
```javascript
@Component({
  selector: 'yourcomponent',
  templateUrl: 'yourcomponent.html',
  providers:[Keycloak]
})
```

**Comment by joshisimt** [comment]
Thanks that one gone but two new error is -
`ERROR TypeError: Cannot read property 'get' of undefined
    at Observable._subscribe (index.js:1137)
    at Observable.webpackJsonp.../../../../rxjs/Observable.js.Observable._trySubscribe (Observable.js:171)
    at Observable.webpackJsonp.../../../../rxjs/Observable.js.Observable.subscribe (Observable.js:159)
    at Keycloak.webpackJsonp.../../../../@ebondu/angular2-keycloak/index.js.Keycloak.init (index.js:1112)
    at HomeComponent.webpackJsonp.../../../../../src/app/home/home.component.ts.HomeComponent.ngOnInit (home.component.ts:37)`

`ERROR TypeError: Cannot read property 'charAt' of undefined
    at Function.webpackJsonp.../../../../@ebondu/angular2-keycloak/index.js.Keycloak.getRealmUrl (index.js:879)
    at Function.webpackJsonp.../../../../@ebondu/angular2-keycloak/index.js.Keycloak.createLoginUrl (index.js:817)
    at DefaultAdapter.webpackJsonp.../../../../@ebondu/angular2-keycloak/index.js.DefaultAdapter.login (index.js:36)
    at Function.webpackJsonp.../../../../@ebondu/angular2-keycloak/index.js.Keycloak.login (index.js:653)
    at HomeComponent.webpackJsonp.../../../../../src/app/home/home.component.ts.HomeComponent.login`

**Comment by ebondu** [comment]
Can you check the keycloak.json file is correcly loaded by the lib on init ?

**Comment by joshisimt** [comment]
Yes I have kept my keycloak.json parallet to package.json file and given the path like this-
   `  ngOnInit() {
    console.info('APP : initializing home component...');

    this.keycloakAuthz.init();

    // comment or change regarding your app-name
    Keycloak.config = 'keycloak.json';

    this.keycloak.init({
      checkLoginIframe: false
    });
  }
`

**Comment by ebondu** [comment]
Depending your packaging options, the file may not be accessible by http. Can you see the success of this http call?

**Comment by joshisimt** [comment]
Which http call ?

**Comment by ebondu** [comment]
You should see something like http://localhost:4200/myapp/keycloak.json corresponding to the call to load the keycloak.json. If the request is 404, then the lib can not initialize.

**Comment by joshisimt** [comment]
not getting 404, but redirect to home page.
and got the below error-
`ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'keycloak.json'
Error: Cannot match any routes. URL Segment: 'keycloak.json'
    at ApplyRedirects.webpackJsonp.../../../router/@angular/router.es5.js.ApplyRedirects.noMatchError (router.es5.js:1356)
`

**Comment by joshisimt** [comment]
![image](https://user-images.githubusercontent.com/7058144/28072046-06043d62-6652-11e7-9680-05c1d47341a3.png)

Attached the screenshot for your reference.

**Comment by ebondu** [comment]
So that's the problem, you must make the keycloak.json file accessible. Have a look to your webpack conf to include it or place the file in the assets folder and then adapt the path if needed in the init method.

**Comment by joshisimt** [comment]
this is not webpack project, i have created new angular cli project using ng new

**Comment by joshisimt** [comment]
I have not created project with webpack, it's angular cli project with using ng new

**Comment by ebondu** [comment]
The new angular-cli is now using webpack... BTW, by placing the keycloak.json at the right place, you should be able to access it.

**Comment by joshisimt** [comment]
I have copied inside assets folder and others folder as well and changed the path as well in code.
Still same error.

**Comment by ebondu** [comment]
What about the http call? Can see the keycloak.json served correctly ?

**Comment by joshisimt** [comment]
no still not, even if see the package.json file using http it don't display and redirect to home page.

**Comment by carlosthe19916** [comment]
I have also had this problem but I solved it changing the module import like this:

```
@NgModule({
  bootstrap: [AppComponent],
  declarations: [
    AppComponent,
  ],
  imports: [
    BrowserModule,
    HttpModule,
    FormsModule,
    Ng2KeycloakModule.forRoot(),
  ],
  providers: [
    Keycloak,
    KeycloakAuthorization,
  ]
})
```
The difference is Ng2KeycloakModule.forRoot() instead of just Ng2KeycloakModule . Also is important to declare providers for Keycloak and KeycloakAuthorization(Optional)

**Comment by joshisimt** [comment]
Hi,

Unforunately still same problem by doing above-
`
core.es5.js:1020 ERROR Response {_body: "<!DOCTYPE html>↵<html lang="en">↵<head>↵<meta char…>Cannot GET /keycloak.json</pre>↵</body>↵</html>↵", status: 404, ok: false, statusText: "Not Found", headers: Headers…}
defaultErrorLogger @ core.es5.js:1020
webpackJsonp.../../../core/@angular/core.es5.js.ErrorHandler.handleError @ core.es5.js:1080
next @ core.es5.js:4502
schedulerFn @ core.es5.js:3635
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:238
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.next @ Subscriber.js:185
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber._next @ Subscriber.js:125
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber.next @ Subscriber.js:89
webpackJsonp.../../../../rxjs/Subject.js.Subject.next @ Subject.js:55
webpackJsonp.../../../core/@angular/core.es5.js.EventEmitter.emit @ core.es5.js:3621
onHandleError @ core.es5.js:3912
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.handleError @ zone.js:395
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:194
ZoneTask.invoke @ zone.js:486
HomeComponent.html:2 ERROR TypeError: Cannot read property 'charAt' of undefined
    at Function.webpackJsonp.../../../../@ebondu/angular2-keycloak/index.js.Keycloak.getRealmUrl (index.js:879)
    at Function.webpackJsonp.../../../../@ebondu/angular2-keycloak/index.js.Keycloak.createLoginUrl (index.js:817)
    at DefaultAdapter.webpackJsonp.../../../../@ebondu/angular2-keycloak/index.js.DefaultAdapter.login (index.js:36)
    at Function.webpackJsonp.../../../../@ebondu/angular2-keycloak/index.js.Keycloak.login (index.js:653)
    at HomeComponent.webpackJsonp.../../../../../src/app/home/home.component.ts.HomeComponent.login (home.component.ts:43)
    at Object.eval [as handleEvent] (HomeComponent.html:2)
    at handleEvent (core.es5.js:11995)
    at callWithDebugContext (core.es5.js:13456)
    at Object.debugHandleEvent [as handleEvent] (core.es5.js:13044)
    at dispatchEvent (core.es5.js:8599)
View_HomeComponent_1 @ HomeComponent.html:2
webpackJsonp.../../../core/@angular/core.es5.js.DebugContext_.logError @ core.es5.js:13396
webpackJsonp.../../../core/@angular/core.es5.js.ErrorHandler.handleError @ core.es5.js:1080
(anonymous) @ core.es5.js:9214
(anonymous) @ platform-browser.es5.js:2668
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:424
onInvokeTask @ core.es5.js:3881
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:191
ZoneTask.invoke @ zone.js:486
HomeComponent.html:2 ERROR CONTEXT DebugContext_ {view: Object, nodeIndex: 2, nodeDef: Object, elDef: Object, elView: Object}`

Thanks

**Comment by ebondu** [comment]
Hi,
You must to be sure the keycloak.json file is accessible from the served app. Depending where you put the file, you maybe have to check your webpack config (i.e. `webpack.common.js`) to ensure the keycloak.json is copied during packaging: 

```javascript 
plugins: [
            new CopyWebpackPlugin([
                ...
                { from: './src/keycloak.json', to: 'keycloak.json' },
]),
```

**Comment by joshisimt** [comment]
Hi,

I don't have created project using webpack, so I have webpack-config.js.
I added plugins in this file and got below error while running- npm start
Cannot add property plugins, object is not extensible
TypeError: Cannot add property plugins, object is not extensible

Thanks

**Comment by ebondu** [comment]
I guess others files from the assets folder are accessible so it should be easy to manually find the path the keycloak.json file is served from ?

**Comment by joshisimt** [comment]
Hi,

No need to find the path now.
I copied it to assets folder and access to keycloak.
Thanks very much for your help so far.

**Comment by jinnerbichler** [comment]
Hello,
I am experiencing the same problems with 

```
@angular/cli: 1.3.0
node: 8.2.1
os: darwin x64
@angular/animations: 4.3.4
@angular/common: 4.3.4
@angular/compiler: 4.3.4
@angular/core: 4.3.4
@angular/forms: 4.3.4
@angular/http: 4.3.4
@angular/platform-browser: 4.3.4
@angular/platform-browser-dynamic: 4.3.4
@angular/router: 4.3.4
@angular/cli: 1.3.0
@angular/compiler-cli: 4.3.4
@angular/language-service: 4.3.4
```
Has anybody found a solution?

**Comment by dariotortola** [comment]
The error message in my case is the same
![image](https://user-images.githubusercontent.com/16289640/30211717-6dfbea2c-94a2-11e7-9944-5480baecd250.png)

But debugging, what is undefined is http field at Keycloak
![image](https://user-images.githubusercontent.com/16289640/30211760-8a3fd22a-94a2-11e7-88c3-e178fbc6e46b.png)

I think it's related to the fact that Ng2KeycloakModule can't be found in @ebondu/angular2-keycloak and I tried (unsuccesfully) with KeycloakModule
![image](https://user-images.githubusercontent.com/16289640/30211855-dceacb2e-94a2-11e7-8054-2b70de3c9b28.png)

**Comment by ebondu** [comment]
Hi,

@dariotortola , you are right, the module has been renamed to 'KeycloakModule'. KeycloakHttp is in charge to inject the http object in Keycloak class. Did you inject Http somewhere in your project ?
