### ISSUE TITLE
Keycloak is initiated when Http is declared

### ISSUE THREAD

**Issue by spine42** [ebondu/angular2-keycloak#8]
Hey,
It seems the Keycloak object is initiated as soon as the Http library is called... Which is problematic since it fires up with all the basic config and not the one I would like to set.

Any ideas why this is happening ?

Thanks !

**Comment by ebondu** [comment]
Hi,
Do you need to pass your config before calling the Http lib ?
By calling the `keycloak.init()` method inside the 'ngOnInit()' method of your component, you should be able to initialize the Keycloak object with your config before calling the Http service.

**Comment by ebondu** [comment]
Should be fixed since 0.7.0.keycloakAuthz.init() and keycloak.init({}) now must to be called once in ngOnInit. Custom parameters passing during keycloak.init({}) will be correctly used by the lib.
